In [1]:
import numpy as np

In [2]:
print(dir(np))

['ALLOW_THREADS', 'BUFSIZE', 'CLIP', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'WRAP', '_CopyMode', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__deprecated_attrs__', '__dir__', '__doc__', '__expired_functions__', '__file__', '__former_attrs__', '__future_scalars__', '__getattr__', '__git_version__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_builtins', '_distributor_init', '_financial_names', '_get_promotion_state', '_globals'

List VS Numpy (Process Time)

In [3]:
from time import process_time

In [5]:
# List
my_list = [i for i in range(10000)]

start_time = process_time()

my_list = [i+5 for i in my_list]

end_time = process_time()

print(end_time - start_time)

0.001514420999999544


In [7]:
# Numpy
np_list = np.array([i for i in range(10000)])

start_time = process_time()

np_list += 5

end_time = process_time()

print(end_time - start_time)

0.0005485590000002816


Numpy Arrays

In [12]:
my_list = [1,2,3,4,5,6,7,8,9]
print(my_list)
type (my_list)

[1, 2, 3, 4, 5, 6, 7, 8, 9]


list

In [10]:
np_list = np.array([i for i in range(50)])
print(np_list) # notic that numpy array not seperated with comma 👇
type (np_list)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]


numpy.ndarray

# **Creating a dim array**

In [15]:
np_list = np.array([1,2,3,4,5,6,7,8,9])
np_list.shape

(9,)

In [17]:
np_list = np.array([(1,2,3,4),(5,6,7,8)])
print(np_list)
np_list.shape

[[1 2 3 4]
 [5 6 7 8]]


(2, 4)

In [20]:
np_list = np.array([(1,2,3,4),(5,6,7,8)],dtype=float)
print(np_list)
np_list.shape

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


(2, 4)

In [22]:
# create a numpy array of Zeros
x = np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [23]:
# create a numpy array of ones
x = np.ones((4,5))
print(x)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [28]:
# create a numpy array of full item
x = np.full((4,5),"hello")
print(x)

[['hello' 'hello' 'hello' 'hello' 'hello']
 ['hello' 'hello' 'hello' 'hello' 'hello']
 ['hello' 'hello' 'hello' 'hello' 'hello']
 ['hello' 'hello' 'hello' 'hello' 'hello']]


In [34]:
# create a numpy array of ones
x = np.random.random((4,5))
print(x)

[[0.84804491 0.55044146 0.97161847 0.32222148 0.05729531]
 [0.19805601 0.42477635 0.08149358 0.06150955 0.93750907]
 [0.46492056 0.62661048 0.04133687 0.34336063 0.18449754]
 [0.07380437 0.16882118 0.66180366 0.80614708 0.30609742]]


In [45]:
# create random values between range
c = np.random.randint(10,90,(5,5))
print(c)

[[24 24 49 70 22]
 [18 83 31 34 26]
 [42 31 50 55 51]
 [63 61 70 53 47]
 [45 70 76 87 45]]


In [42]:
# create an identity matrix
a = np.eye(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [41]:
# create an identity matrix
a = np.eye(3,3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [38]:
# random integer values array within a specific range
c = np.random.randint(1,50,(3,5))
print(c)

[[23 39 27 19 17]
 [13 41 23 49 25]
 [48 32  2  5 35]]


In [43]:
# array of evenly spaced values --> specifying the number of values required
d = np.linspace(10,30,5)
print(d)

[10. 15. 20. 25. 30.]


In [44]:
# array of evenly spaced values --> specifying the step
e = np.arange(10,30,5)
print(e)

[10 15 20 25]


In [ ]:
# convert a list to a numpy array
list2 = [10,20,20,20,50]

np_array = np.asarray(list2)
print(np_array)
type(np_array)

[10 20 20 20 50]


numpy.ndarray

Analysing a numpy array

In [ ]:
c = np.random.randint(10,90,(5,5))
print(c)

[[66 80 57 82 62]
 [61 81 62 75 65]
 [24 43 42 35 11]
 [64 70 50 80 45]
 [70 23 53 80 23]]


In [ ]:
# array dimension
print(c.shape)

(5, 5)


In [ ]:
# number of dimensions
print(c.ndim)

2


In [ ]:
# number of elements in an array
print(c.size)

25


In [ ]:
# checking the data type of the values in the array
print(c.dtype)

int64


Mathematical operations on a np array

In [ ]:
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]

print(list1 + list2)    # concatenate or joins two list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [ ]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))

In [ ]:
print(a)
print(b)

[[7 2 0]
 [8 8 6]
 [5 7 0]]
[[15 10 13]
 [18 14 14]
 [12 13 10]]


In [ ]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[22 12 13]
 [26 22 20]
 [17 20 10]]
[[ -8  -8 -13]
 [-10  -6  -8]
 [ -7  -6 -10]]
[[105  20   0]
 [144 112  84]
 [ 60  91   0]]
[[0.46666667 0.2        0.        ]
 [0.44444444 0.57142857 0.42857143]
 [0.41666667 0.53846154 0.        ]]


In [ ]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))

In [ ]:
print(a)
print(b)

[[4 7 7]
 [3 9 9]
 [4 9 7]]
[[11 12 10]
 [19 14 16]
 [10 19 15]]


In [ ]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[15 19 17]
 [22 23 25]
 [14 28 22]]
[[ -7  -5  -3]
 [-16  -5  -7]
 [ -6 -10  -8]]
[[ 44  84  70]
 [ 57 126 144]
 [ 40 171 105]]
[[0.36363636 0.58333333 0.7       ]
 [0.15789474 0.64285714 0.5625    ]
 [0.4        0.47368421 0.46666667]]


Array Manipulation

In [ ]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[1 2 2]
 [8 0 7]]
(2, 3)


In [ ]:
# transpose
trans = np.transpose(array)
print(trans)
print(trans.shape)

[[1 8]
 [2 0]
 [2 7]]
(3, 2)


In [ ]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[8 1 0]
 [2 5 9]]
(2, 3)


In [ ]:
trans2 = array.T
print(trans2)
print(trans2.shape)

[[8 2]
 [1 5]
 [0 9]]
(3, 2)


In [ ]:
# reshaping a array
a = np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[4 3 7]
 [4 6 6]]
(2, 3)


In [ ]:
b = a.reshape(3,2)
print(b)
print(b.shape)

[[4 3]
 [7 4]
 [6 6]]
(3, 2)
